Support REMOVE_ON_FAILURE option to cet_test.

diff --git a/bin/cet_exec_test b/bin/cet_exec_test
--- a/bin/cet_exec_test
+++ b/bin/cet_exec_test
@@ -12,10 +12,15 @@ function realdir() {
 }
 
 prog=${0##*/}
+fill=${prog//?/ }
 
 function usage() {
   cat 1>&2<<EOF
-usage: $prog [--required-files <files>] --wd <test-working-dir> --datafiles <;-separated-datafiles> [--] <cmd> [<args>...]
+usage: $prog [--datafiles <files>] [--remove-on-failure <files>] \
+       $fill [--required-files <files>] [--wd <test-working-dir>] [--] \
+       $fill <cmd> [<args>...]
+
+Multiple <files> should be separated with semicolons (;).
 EOF
   exit ${1:-1}
 }
@@ -23,7 +28,7 @@ EOF
 declare -a datafiles
 function set_datafiles() {
   local IFS=';'
-  for i in ${1}; do datafiles[${#datafiles[@]}]=$(basename "$i"); done
+  for i in ${1}; do datafiles+=("$(basename "$i")"); done
 }
 
 getopt -T >/dev/null 2>&1                                               
@@ -32,7 +37,7 @@ if (( $? != 4 )); then
   exit 1                                                                
 fi                                                                      
 
-TEMP=`getopt -n "$prog" --long datafiles:,debug,required-files:,skip-return-code:,wd: -o + -- "${@}"`
+TEMP=`getopt -n "$prog" --long datafiles:,debug,remove-on-failure:,required-files:,skip-return-code:,wd: -o + -- "${@}"`
 eval set -- "$TEMP"
 
 while true; do
@@ -44,6 +49,10 @@ while true; do
         --debug)
             vopt="v"
             shift;
+            ;;
+        --remove-on-failure)
+            old_IFS="${IFS}"; IFS=';'; removeOnFailure=($2); IFS=${old_IFS}
+            shift; shift;
             ;;
         --required-files)
             old_IFS="${IFS}"; IFS=';'; requiredfiles=($2); IFS=${old_IFS}
@@ -99,15 +108,9 @@ done
 
 # Make sure required files exist.
 declare -a missingfiles
-for i in "${requiredfiles[@]}"; do
+for i in "${requiredfiles[@]}" "${datafiles[@]}"; do
   if [[ ! -e "$i" ]]; then
-    missingfiles[${#missingfiles[@]}]=$i
-  fi
-done
-
-for i in "${datafiles[@]}"; do
-  if [[ ! -e "$i" ]]; then
-    missingfiles[${#missingfiles[@]}]=$i
+    missingfiles+=("${i}")
   fi
 done
 
@@ -116,5 +119,11 @@ if (( ${#missingfiles[@]} )); then
   exit ${skip_code:-247}
 else
   # Execute command in now-clean environment.
-  exec "$@"
+  "$@"
+  status=$?
+  if (( ${status} != 0 )) && (( ${#removeOnFailure[@]} > 0 )); then
+    echo "Removing due to failed execution: ${removeOnFailure[@]}" 1>&2
+    rm -rf "${removeOnFailure[@]}"
+  fi
+  exit ${status}
 fi
