Bootstrap is now compatible with building with MRB 6
* Paths (source_base, build_base), are calculated to work with
  standalone or MRB builds of cetmodules.

* Improve modularity with time_cmd_and_report_status() and
  time_cmd_and_require_success().

* Account for non-itemized time in final total.

* bootstrap-perl-env writes a dependency (.d) file and timestamp file
  for invocation from a custom CMake command / target. Dependency file
  is deleted on failure.

* Optionally look for and/or generate minimal and/or version-specific
  "cetmodules_devel" tarballs (*not* UPS products) to vastly speed up
  clean builds, CI, etc.

diff --git a/libexec/bootstrap-perl-env b/libexec/bootstrap-perl-env
--- a/libexec/bootstrap-perl-env
+++ b/libexec/bootstrap-perl-env
@@ -10,26 +10,32 @@
 # Functions
 ########################################################################
 
-bootstrap_local_lib() {
-  [ -f "$cpan_export/lib/perl5/local/lib.pm" ] && \
-    [ -f "$cpan_export/lib/perl5/CPAN/MyConfig.pm" ] && return
+# Add fully-qualified paths as dependencies of our stamp file.
+add_to_depfile() {
+  [ -n "$*" ] || return
+  local file=
+  for file in ${*:+"$@"}; do
+    echo "$stampfile: $(real_path "$file")"
+  done >> "$depfile"
+}
+
+# Bootstrap local::lib (also CPAN if missing).
+bootstrap_local_lib() (
+  # Change directory to temporary working area.
+  cd "$cpan_tmp" || return
 
   # Copy our CPAN configuration into a place where it will be found.
   mkdir -p "$cpan_export/lib/perl5/CPAN"
-  cp "$CETPKG_SOURCE/config/MyConfig.pm" "$cpan_export/lib/perl5/CPAN/"
+  cp "$source_base/config/MyConfig.pm" "$cpan_export/lib/perl5/CPAN/"
 
-  # Bootstrap local::lib (also CPAN if missing).
   local local_lib_url="https://metacpan.org/pod/local::lib"
-  local local_lib_download_url="$({ curl --insecure --fail "$local_lib_url" || \
-wget --no-check-certificate "$local_lib_url"; } 2>/dev/null | \
+  local local_lib_download_url="$( http_get "$local_lib_url" | \
 sed -nEe '/itemprop="downloadUrl"/ s&^.*href="([^"]+)".*$&\1&p')"
 
   [ -n "$local_lib_download_url" ] || \
     error "unable to locate download URL for local::lib on CPAN" || return
 
-  { curl --insecure --fail "$local_lib_download_url" || \
-      wget --no-check-certificate "$local_lib_download_url"; } 2>/dev/null | \
-    tar zx || \
+  http_get "$local_lib_download_url" | tar zx || \
     error "unable to download local::lib from $local_lib_download_url" || \
     return
 
@@ -42,66 +48,112 @@ sed -nEe '/itemprop="downloadUrl"/ s&^.*href="([^"]+)".*$&\1&p')"
       inc/CPANBootstrapper.pm
   { perl Makefile.PL --bootstrap="$cpan_export" && make test && make install; } 2>&1 \
     || return;
-  cd - >/dev/null
-}
+)
 
 # Install packages without running all the tests.
-cpan() {
-  perl -MCPAN ${*:+-e 'CPAN::Shell->notest(@ARGV)' "$@"} 2>&1
+cpan_install() {
+  perl -MCPAN ${*:+-e 'CPAN::Shell->notest(@ARGV)' install "$@"} 2>&1
 }
 
-double_print() {
+# Print message to STDOUT _and_ STDERR.
+printit_double() {
+  printit ${*:+"$@"}
+  printit ${*:+"$@"} 1>&2
+}
+
+# Print error message to STDOUT _and_ STDERR.
+error() {
+  local $status=$?
+  printit "ERROR: " ${*:+"$@"} 1>&2
+  return $status
+}
+
+# Exit with error message and non-zero status.
+error_exit() {
+  local status=$?
+  (( status == 0 )) && status=1
+  (( TIME_TOTAL += SECONDS ))
+  [ -n "$*" ] && printit "ERROR: " 1>&2
+  printit "ERROR: " \
+          "exit with status $status after (%d:%02d)" \
+          $((TIME_TOTAL / 60)) $((TIME_TOTAL % 60)) 1>&2
+  exit $status
+}
+
+get_and_expand() {
+  local url="$1"; shift
+  http_get "$url" | tar "$@"
+} 2>/dev/null
+
+# Download given URL to STDOUT.
+http_get() {
+  local url="$1"
+  curl --insecure --silent --fail "$url" || \
+    wget --no-check-certificate -q "$url"
+} 2>/dev/null
+
+# Print INFO message.
+info() {
+  local status=$?
+  [ -n "$*" ] && printit "INFO: " "$@"
+  return $status
+}
+
+# Install/upgrade prerequisites for given Perl modules.
+install_modules_for() {
+  local needed_modules=($(needed_modules "$@"))
+  (( ${#needed_modules[@]} == 0)) || \
+    cpan_install ${needed_modules[*]:+"${needed_modules[@]}"}
+}
+
+# Ascertain prerequisites for given Perl modules.
+needed_modules() {
+  # Note that we do *NOT* use "-c" option to scandeps.pl: it will stall
+  # indefinitely processing Tagging.pm, which has a function that is
+  # executed at compile-time.
+  add_to_depfile ${*:+"$@"}
+  PERL5LIB="$source_base/libexec${PERL5LIB:+:$PERL5LIB}" \
+          scandeps.pl -R -V -T -C "$cpan_base/scandeps-cache.dat" -- \
+          "$@" 2>&1 | \
+    sed -En \
+        -e "s&^'([^']+)'[^#]+#[[:space:]]+([^[:space:]S?]+.*)#[[:space:]]+[^[:space:]]+.*\$&\\1&
+t printit
+s&^#[[:space:]]+[Cc]ould[[:space:]]+not[[:space:]]+find[[:space:]]+source[[:space:]]+file[[:space:]]+'([^']+)\.pm'.*\$&\\1&
+T
+: scopeit
+s&/&::&
+t scopeit
+: printit
+p"
+} 2>/dev/null
+
+printit() {
   local prefix="$(printf "$1")"; shift
   local msg="$(printf "$@")"
   msg="${msg%$'\n'}"
   if [ -z "$msg" ]; then
     echo "${prefix/%: /!}"
-    echo "${prefix/%: /!}" 1>&2
   else
     echo "$prefix${msg//$'\n'/$'\n'$prefix}"
-    echo "$prefix${msg//$'\n'/$'\n'$prefix}" 1>&2
   fi
 }
 
-error() {
-  local $status=$?
-  double_print "ERROR: " ${*:+"$@"}
-  return $status
+real_path() {
+  local path="$1"
+  local file=
+  if ! [ -d "$path" ]; then
+    file="${path##*/}"
+    path="${path%${file}}"
+  fi
+  if cd "${path:-.}"; then
+    echo "$(pwd -P)${file:+/$file}"
+    cd - >/dev/null
+  fi
 }
 
-error_exit() {
-  local status=$?
-  (( status == 0 )) && status=1
-  (( TIME_TOTAL += SECONDS ))
-  [ -n "$*" ] && double_print "ERROR: "
-  double_print "ERROR: " \
-               "exit with status $status after (%d:%02d)" \
-               $((TIME_TOTAL / 60)) $((TIME_TOTAL % 60))
-  exit $status
-}
-
-info() {
-  local status=$?
-  [ -n "$*" ] && double_print "INFO: " "$@"
-  return $status
-}
-
-install_modules_for() {
-  local needed_modules=($(needed_modules "$@"))
-  (( ${#needed_modules[@]} == 0)) || \
-    cpan install ${needed_modules[*]:+"${needed_modules[@]}"}
-}
-
-needed_modules() {
-  # Do *NOT* use "-c" option to scandeps.pl: it will stall indefinitely
-  # processing Tagging.pm, which has a function that is executed at
-  # compile-time.
-  PERL5LIB="$CETPKG_SOURCE/libexec${PERL5LIB:+:$PERL5LIB}" \
-          scandeps.pl -R -V -T -C "$cpan_base/scandeps-cache.dat" "$@" | \
-    sed -Ene "s/^'([^']+)'[^#]+#[[:space:]]+([^[:space:]S?]+.*)#[[:space:]]+[^[:space:]]+.*\$/\\1/p"
-} 2>/dev/null
-
-time_and_check() {
+# Execute and time the specified actions bracketed by the given message
+# and report status.
+time_cmd_and_report_status() {
   local msg="$1"; shift
   local status_flag=OK
   (( TIME_TOTAL += SECONDS ))
@@ -112,8 +164,13 @@ time_and_check() {
   (( status == 0 )) || status_flag=FAILED
   local time=$(( SECONDS ))
   (( TIME_TOTAL += time ))
+  (( SECONDS = 0 ))
   info "$msg...$status_flag (%d:%02d)" $((time / 60)) $((time % 60))
-  (( status == 0 )) || error_exit
+  return $status
+}
+
+time_cmd_and_require_success() {
+  time_cmd_and_report_status "$@" || error_exit
 }
 
 ########################################################################
@@ -123,41 +180,88 @@ time_and_check() {
 (( TIME_TOTAL = 0 ))
 (( SECONDS = 0 ))
 
-# Sanity check
-[ -n "$CETPKG_SOURCE" ] || error_exit "CETPKG_SOURCE must be defined"
-[ -n "$CETPKG_BUILD" ] || error_exit "CETPKG_BUILD must be defined"
-[ -n "$CET_SUBDIR" ] || error_exit "CET_SUBDIR must be defined - missing cetpkgsupport?"
+# Sanity checks.
+[ -n "$CET_SUBDIR" ] || \
+  error_exit "CET_SUBDIR must be defined - missing cetpkgsupport?"
 
-cpan_base="$CETPKG_BUILD/$CET_SUBDIR"
+# Locations.
+arch="${CET_SUBDIR//\./-}"
+build_base="$(real_path)"
+source_base="$(real_path ${BASH_SOURCE%/*/*})"
+cpan_base="$build_base/$CET_SUBDIR"
 cpan_build="$cpan_base/cpan_build"
 cpan_export="$cpan_base/CPAN"
 cpan_tmp="$cpan_base/.cpan/tmp"
+depfile="$cpan_tmp/${cpan_export##*/}.d"
+stampfile="$cpan_tmp/CPAN.stamp"
 
-info "bootstrapping Perl environment for cetmodules (may take >=15 minutes for a pristine install)..."
-mkdir -p "$cpan_tmp" && cd "$cpan_tmp" || \
-    error_exit "unable to prepare temporary work area $cpan_tmp"
+# Prepare work area.
+info "initializing Perl environment for cetmodules..."
+mkdir -p "$cpan_tmp" && \
+  cd "$cpan_tmp" || \
+    error_exit "unable to prepare temporary working area $cpan_tmp"
+cd - >/dev/null
 
-####################################
-# Bootstrap CPAN, etc.
-####################################
+# Delete depfile if we exit before we're ready.
+trap "[ -n \"$depfile\" ] && rm -f -- \"$depfile\"" EXIT
+rm -f "$depfile"
 
-time_and_check   "bootstrapping a local::lib Perl environment for cetmodules"
+add_to_depfile "$BASH_SOURCE"
+
+# Bootstrap.
+cetmodules_dotversion="$(cat "$source_base/VERSION")"
+cetmodules_version=v${cetmodules_dotversion%%-*}
+cetmodules_version=${cetmodules_version//./_}
+[ "$cetmodules_dotversion" = "${cetmodules_dotversion#*-}" ] || \
+  cetmodules_version+="${cetmodules_dotversion#*-}"
+cetmodules_devel_archive_minimal=cetmodules_devel-minimal-$arch.tar.bz2
+cetmodules_devel_archive=cetmodules_devel-$cetmodules_dotversion-$arch.tar.bz2
+cetmodules_devel_url="${CETMODULES_DEVEL_URL-https://scisoft.fnal.gov/scisoft/packages/cetmodules_devel/$cetmodules_version/$cetmodules_devel_archive}"
+
+if [ -z "$cetmodules_devel_url" ]; then
+  info "download of cetmodules_devel disabled: clean rebuild of required PERL packages" 1>&2
+  rm -rf "$cpan_build" "$cpan_export"
+  no_download=1
+  save_minimal=1
+fi
+
+if ! [ -d "$cpan_export" ]; then
+  ! (( no_download )) && \
+    { time_cmd_and_report_status \
+        "[OPTIONAL] obtain and expand pre-built Perl archive for cetmodules $cetmodules_dotversion-$arch" \
+        get_and_expand "$cetmodules_devel_url" jx || \
+        { time_cmd_and_report_status \
+            "[OPTIONAL] obtain and expand minimal pre-built Perl archive for cetmodules $arch" \
+            get_and_expand "${cetmodules_devel_url%/*/*}/vminimal/$cetmodules_devel_archive_minimal" jx && \
+            save_minimal=1
+        }
+    } || \
+      { (( no_download )) || \
+          info "pre-built CPAN environment not available: clean rebuild of all required PERL packages\n" \
+               "  (may take >=25 minutes for a pristine install)" 1>&2
+        save_minimal=1
+        time_cmd_and_require_success \
+          "bootstrapping a local::lib Perl environment for cetmodules" \
+          bootstrap_local_lib
+      }
+fi
 
 # Set up the environment to use our installed Perl modules.
 eval "$(perl -I"$cpan_export/lib/perl5" -Mlocal::lib="$cpan_export" 2>/dev/null)" || \
   error_exit "unable to set up environment to find locally-installed Perl modules"
 
 ####################################
-# Update and enhance CPAN.
-(( SECONDS = 0 ))
-info "install/verify Perl distribution tools for cetmodules..."
-{ cpan install YAML CPAN::SQLite && \
-  cpan install Log::Log4perl ExtUtils::CBuilder CPAN; } </dev/null || status=FAILED
-(( TIME = SECONDS ))
-(( TIME_TOTAL += TIME ))
-info "install/verify Perl distribution tools for cetmodules...${status:-OK} (%d:%02d)" \
-       $((TIME / 60)) $((TIME % 60))
-[ -z "${status}" ] || exit 1
+# Update and enhance CPAN and friends.
+time_cmd_and_require_success \
+  "install/verify Perl distribution tools for cetmodules (1/2)" \
+  cpan_install YAML CPAN::SQLite
+
+time_cmd_and_require_success \
+  "install/verify Perl distribution tools for cetmodules (2/2)" \
+  cpan_install Log::Log4perl ExtUtils::CBuilder \
+  Term::ReadLine::Perl CPAN
+
+time_cmd_and_require_success "verify local::lib" cpan_install local::lib
 ####################################
 
 eval "$(perl -Mlocal::lib="$cpan_build" 2>/dev/null)" || \
@@ -165,14 +269,27 @@ eval "$(perl -Mlocal::lib="$cpan_build" 2>/dev/null)" || \
 
 ####################################
 # Build-only CPAN tools
-(( SECONDS = 0 ))
-info "install/verify build-only CPAN tools"
-{ cpan install CPANPLUS Module::ScanDeps App::pmuninstall; } </dev/null || status=FAILED
-(( TIME = SECONDS ))
-(( TIME_TOTAL += TIME ))
-info "install/verify build-only CPAN tools...${status:-OK} (%d:%02d)" \
-       $((TIME / 60)) $((TIME % 60))
-[ -z "${status}" ] || exit 1
+time_cmd_and_require_success \
+  "install/verify build-only CPAN tools" \
+  cpan_install CPANPLUS Module::ScanDeps App::pmuninstall
+####################################
+
+####################################
+# Modules for development, build, and test infrastructure.
+time_cmd_and_require_success \
+  "install/verify Perl modules for cetmodules development/build/test" \
+  cpan_install Perl::Tidy B::Lint {Test,Task}::Perl::Critic
+####################################
+
+####################################
+# If we have built a clean minimal environment, save it.
+if (( save_minimal )); then
+  time_cmd_and_require_success \
+    "create/refresh minimal cetmodules_devel archive $cetmodules_devel_archive_minimal" \
+    tar jcf "$cetmodules_devel_archive_minimal" -C "$build_base" -- \
+    "$CET_SUBDIR/"{"${cpan_export##*/}","${cpan_build##*/}"}
+fi
+####################################
 
 # Set up the environment to install Perl modules for export.
 eval "$(perl -Mlocal::lib="$cpan_export" 2>/dev/null)" || \
@@ -180,40 +297,42 @@ eval "$(perl -Mlocal::lib="$cpan_export" 2>/dev/null)" || \
 
 ####################################
 # Modules required for operation.
-(( SECONDS = 0 ))
-info "install/verify Perl modules required by cetmodules tools for export..."
-install_modules_for \
-  $(find  "$CETPKG_SOURCE/libexec" -name '*.pm') \
-  "$CETPKG_SOURCE/libexec/set_dev_products" \
-  "$CETPKG_SOURCE/tools/migrate" || status=FAILED
-(( TIME = SECONDS ))
-(( TIME_TOTAL += TIME ))
-info "install/verify Perl modules required by cetmodules tools for export...${status:-OK} (%d:%02d)" \
-       $((TIME / 60)) $((TIME % 60))
-[ -z "${status}" ] || exit 1
+time_cmd_and_require_success \
+  "install/verify Perl modules required by cetmodules tools for export" \
+  install_modules_for \
+  $(find  "$source_base/libexec" -name '*.pm') \
+  "$source_base/libexec/set_dev_products" \
+  "$source_base/tools/migrate"
 ####################################
 
-# Revert environment for dev/build/test requirements.
+# Revert environment to install more modules for development.
 eval "$(perl -Mlocal::lib="$cpan_build" 2>/dev/null)" || \
   error_exit "unable to reset environment for installation of build-only Perl modules"
 
 ####################################
-# Modules for development, build and test.
-(( SECONDS = 0 ))
-info "install/verify Perl modules for cetmodules development/build/test..."
-cpan install Perl::Tidy B::Lint {Test,Task}::Perl::Critic \
-  && install_modules_for "$CETPKG_SOURCE/test/"{Modules,libexec}/*_t \
-    || status=FAILED
-(( TIME = SECONDS ))
-(( TIME_TOTAL += TIME ))
-info "install/verify Perl modules for cetmodules development/build/test...${status:-OK} (%d:%02d)" \
-       $((TIME / 60)) $((TIME % 60))
-[ -z "${status}" ] || exit 1
+# Test prerequisites.
+time_cmd_and_require_success \
+  "install/verify Perl modules required by cetmodules tests" \
+  install_modules_for "$source_base/test/"{Modules,libexec}/*_t
 ####################################
 
+####################################
+# Save the full Perl environment as a version-tagged archive
+time_cmd_and_require_success \
+  "create/refresh cetmodules_devel archive $cetmodules_devel_archive" \
+  tar jcf "$cetmodules_devel_archive" -C "$build_base" -- \
+  "$CET_SUBDIR/"{"${cpan_export##*/}","${cpan_build##*/}"}
+####################################
+
+(( TIME_TOTAL += SECONDS ))
+
 # Done.
-info "bootstrapping Perl environment for cetmodules...COMPLETE (%d:%02d)" \
+info "initializing Perl environment for cetmodules...COMPLETE (%d:%02d)" \
        $((TIME_TOTAL / 60)) $((TIME_TOTAL % 60))
+
+# Clear trap so depfile remains upon success.
+trap "" EXIT
+touch "$stampfile"
 
 ### Local Variables:
 ### mode: sh
